language: php
dist: trusty

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: deps=no
    - php: 7
      env: deps=no
    - php: 7.1
      env: deps=no

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_install:
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - composer self-update
  - if [ "$deps" = "no" ]; then composer --prefer-dist install; fi;
  - if [ "$deps" = "high" ]; then composer --prefer-source update; fi;
  - ./vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp;

script:
  - ./vendor/bin/phpcs . --ignore=vendor/ --standard=MEQP2;
