sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix

language: php

env:
  global:
      - PhpApi=~17.4.13
      - PhpCustomerMessages=~17.2.3
matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: magento=2.0.1
    - php: 5.6
      env: magento=2.1.1
    - php: 7.0
      env: magento=2.1.6

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_install:
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - cd ..
  - composer self-update
  - composer create-project "magento/community-edition:$magento" magento-ce
  - cd "magento-ce"
  - mysql -uroot -e 'CREATE DATABASE magento2;'
  - php bin/magento setup:install -q --admin-user="admin" --admin-password="123123q" --admin-email="admin@example.com" --admin-firstname="John" --admin-lastname="Doe"
  - mkdir -p "./app/code/Heidelpay/Gateway"
  - cp -r ../magento2 ./app/code/Heidelpay/Gateway/
  - composer require "heidelpay/php-api:$PhpApi"
  - composer require "heidelpay/php-customer-messages:$PhpCustomerMessages"
  - php -f bin/magento module:enable Heidelpay_Gateway
  - php -f bin/magento setup:upgrade
  - php -f bin/magento cache:flush
  - php -f bin/magento setup:di:compile
  - php -f bin/magento setup:static-content:deploy
  - pwd
  - ls -la
  - cd ../magento2
  - composer update
  - ./vendor/bin/phpcs --config-set installed_paths vendor/magento/marketplace-eqp;

script:
  - ./vendor/bin/phpcs . --ignore=vendor/ --standard=MEQP2;
