# automated extension test for different magento 2 version
# Use of this software requires acceptance of the Evaluation License Agreement. See LICENSE file.
# Copyright © 2016-present Heidelberger Payment GmbH. All rights reserved.
# https://dev.heidelpay.de/magento2
# Jens Richter
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
    - postfix
language: php
php:
  - 5.6
  - 7.0
env:
  global:
    - INTEGRATION_SETS=3
  matrix:
    - magento=2.0.0
    - magento=2.0.1
    - magento=2.0.2
    - magento=2.0.3
    - magento=2.0.4
    - magento=2.0.5
    - magento=2.0.6
    - magento=2.0.7
    - magento=2.0.8
    - magento=2.0.9
    - magento=2.0.10
    - magento=2.0.11
    - magento=2.0.12
    - magento=2.0.13
    - magento=2.1.0
    - magento=2.1.1
    - magento=2.1.2
    - magento=2.1.3
    - magento=2.1.4
    - magento=2.1.5
    - magento=2.1.6
matrix:
  fast_finish: true
  exclude:
    - php: 5.6
      env: magento=2.1.6
cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local
before_install:
  - composer config -g http-basic.repo.magento.com $MAGE_PUBLICKEY $MAGE_PRIVATEKEY
  - chmod +x ./dev/travis/*
  - ./dev/travis/before_install.sh
before_script: ./dev/travis/before_script.sh
script: ./dev/travis/script.sh
